name: 'Upload Episode from YouTube To Anchor.Fm'
on:
  push:
    paths: 
      - episode.json
    branches: [master]
jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Anchor.Fm
        uses: zephyrus3/youtube-to-anchorfm@custom-desc-and-title
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: ${{ secrets.EPISODE_PATH }}
